FROM hypriot/rpi-python

RUN apt-get update
RUN apt-get -y install python-pip
RUN apt-get -y install build-essential libffi-dev libxml2-dev libxslt1-dev python-dev
COPY requirements.txt packtpub/requirements.txt
COPY ./src packtpub/src
RUN pip install -r packtpub/requirements.txt
WORKDIR packtpub/src

CMD python start.py
